# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: time cockpit
email: support@time-cockpit.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/time-cockpit-website" # the subpath of your site, e.g. /blog
url: "https://www.timecockpit.com" # the base hostname & protocol for your site
twitter_username: timecockpit
github_username:  software-architects

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, time-cockpit-website.sln, 
additional_content,
content/en/blog/2014/09,
content/en/blog/2015/02,
content/en/blog/2012/11,
content/en/blog/2014/02,
content/en/blog/2014/10,
content/en/blog/2014/06,
content/en/blog/2014/12,
content/en/blog/2014/07,
content/en/blog/2014/01,
content/en/blog/2014/05,
content/en/blog/2014/11,
content/en/blog/2014/08/28,
content/en/blog/2013,
content/en/blog/2011,
content/en/blog/2008,
content/en/blog/2009,
content/en/blog/2010,
content/en/blog/2012,

content/en/blog/2016/05/1,
content/en/blog/2016/04/10,
content/en/blog/2015/12/29,
content/en/blog/2015/06/29,
content/en/blog/2015/03/30,
content/en/blog/2015/10/31,
content/en/blog/2015/03/22,
content/en/blog/2015/09/30,
content/en/blog/2016/06/29
]
